apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sentiment-model"
spec:
  predictor:
    containers:
      - name: kserve-container
        # Thay đường dẫn chuẩn của Mai ở đây
        image: us-central1-docker.pkg.dev/AIDE-FINAL-PROJECT/my-repo/sentiment-api:latest 
        # Cấu hình cổng mà FastAPI của Mai đang lắng nghe (thường là 8000 hoặc 8080)
        ports:
          - containerPort: 8000 
            protocol: TCP
        env:
          - name: STORAGE_URI
            # value: "gs://[BUCKET_NAME]/model" # Nếu Mai để model trong container thì bỏ dòng này
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"